export type SessaoJulgamentoView = {
  id: number;
  numero: string | null;
  dt_realizacao: string | null;
  dt_encerramento: string | null;
  orgao_julgador_id: number | null;
  orgao_julgador: string | null;
  local_sessao: string | null;
  tipo: string | null;
  situacao: string | null;
  numero_publicacao: string | null;
  data_publicacao: string | null;
  tipo_publicacao: string | null;
  arquivo_sessao: string | null;
  qtd_julgado: number | null;
  qtd_vistas: number | null;
  qtd_julgamento: number | null;
};

export type ProcessoPautaJulgamentoView = {
  id: number;
  sessao_id: number | null;
  sessao_numero: string | null;
  processo_id: number | null;
  situacao: string | null;
  sequencia: number | null;
  relator_id: number | null;
  nome_relator: string | null;
  relator_tratamento: string | null;
  revisor_id: number | null;
  nome_revisor: string | null;
  eletronico: string | null;
  qtde_pron: number | null;
  advogado: string | null;
  incluir_interessados: string | null;
  julgado: string | null;
  numero_processo_fmt: string | null;
  objeto: string | null;
  nome_classe: string | null;
  assunto: string | null;
  nome_1_parte: string | null;
  situacao_funcional: string | null;
  nome_orgao: string | null;
};
