-- =============================================================
-- Tabelas auxiliares de classificação orçamentária da despesa
-- Fonte: Portaria Interministerial SOF/STN/MF e Portaria MOG nº 42/1999
-- Executar no SQL Editor do Supabase
-- =============================================================

-- -------------------------------------------------------------
-- 1. Elemento de Despesa
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aux_dim_elemento_despesa (
  codigo   SMALLINT PRIMARY KEY,
  descricao TEXT NOT NULL
);

TRUNCATE public.aux_dim_elemento_despesa;

INSERT INTO public.aux_dim_elemento_despesa (codigo, descricao) VALUES
( 1, 'Aposentadorias, Reserva Remunerada e Reformas'),
( 3, 'Pensões'),
( 4, 'Contratação por Tempo Determinado'),
( 5, 'Outros Benefícios Previdenciários'),
( 6, 'Benefício Mensal ao Deficiente e ao Idoso'),
( 7, 'Contribuição a Entidades Fechadas de Previdência'),
( 8, 'Outros Benefícios Assistenciais'),
(10, 'Seguro Desemprego e Abono Salarial'),
(11, 'Vencimentos e Vantagens Fixas – Pessoal Civil'),
(12, 'Vencimentos e Vantagens Fixas – Pessoal Militar'),
(13, 'Obrigações Patronais'),
(14, 'Diárias – Civil'),
(15, 'Diárias – Militar'),
(16, 'Outras Despesas Variáveis – Pessoal Civil'),
(17, 'Outras Despesas Variáveis – Pessoal Militar'),
(18, 'Auxílio Financeiro a Estudantes'),
(19, 'Auxílio-Fardamento'),
(20, 'Auxílio Financeiro a Pesquisadores'),
(21, 'Juros sobre a Dívida por Contrato'),
(22, 'Outros Encargos sobre a Dívida por Contrato'),
(23, 'Juros, Deságios e Descontos da Dívida Mobiliária'),
(24, 'Outros Encargos sobre a Dívida Mobiliária'),
(25, 'Encargos sobre Operações de Crédito por ARO'),
(26, 'Obrigações decorrentes de Política Monetária'),
(27, 'Encargos pela Honra de Avais, Garantias, Seguros e Similares'),
(28, 'Remuneração de Cotas de Fundos Autárquicos'),
(29, 'Distribuição de Resultado de Empresas Estatais Dependentes'),
(30, 'Material de Consumo'),
(31, 'Premiações Culturais, Artísticas, Científicas e Desportivas'),
(32, 'Material, Bem ou Serviço para Distribuição Gratuita'),
(33, 'Passagens e Despesas com Locomoção'),
(34, 'Outras Despesas de Pessoal decorrentes de Terceirização'),
(35, 'Serviços de Consultoria'),
(36, 'Outros Serviços de Terceiros – Pessoa Física'),
(37, 'Locação de Mão-de-Obra'),
(38, 'Arrendamento Mercantil'),
(39, 'Outros Serviços de Terceiros – Pessoa Jurídica'),
(41, 'Contribuições'),
(42, 'Auxílios'),
(43, 'Subvenções Sociais'),
(45, 'Subvenções Econômicas'),
(46, 'Auxílio-Alimentação'),
(47, 'Obrigações Tributárias e Contributivas'),
(48, 'Outros Auxílios Financeiros a Pessoas Físicas'),
(49, 'Auxílio-Transporte'),
(51, 'Obras e Instalações'),
(52, 'Equipamentos e Material Permanente'),
(53, 'Aposentadorias do RPPS e Reformas dos Militares'),
(54, 'Aquisição de Imóveis'),
(61, 'Aquisição de Imóveis'),
(62, 'Aquisição de Produtos para Revenda'),
(63, 'Aquisição de Títulos de Crédito'),
(64, 'Aquisição de Títulos Representativos de Capital já Integralizado'),
(65, 'Constituição ou Aumento de Capital de Empresas'),
(66, 'Concessão de Empréstimos e Financiamentos'),
(67, 'Depósitos Compulsórios'),
(71, 'Principal da Dívida Contratual Resgatado'),
(72, 'Principal da Dívida Mobiliária Resgatado'),
(73, 'Correção Monetária ou Cambial da Dívida Contratual Resgatada'),
(74, 'Correção Monetária ou Cambial da Dívida Mobiliária Resgatada'),
(75, 'Correção Monetária da Dívida de Operações de Crédito por ARO'),
(76, 'Principal Corrigido da Dívida Mobiliária Refinanciado'),
(77, 'Principal Corrigido de Operações de Crédito Especiais Refinanciado'),
(81, 'Distribuição Constitucional ou Legal de Receitas'),
(82, 'Aporte de Recursos pelo Parceiro Público em PPP'),
(83, 'Despesas decorrentes de Contrato de PPP'),
(84, 'Despesas de Capital Decorrentes de PPP'),
(91, 'Sentenças Judiciais'),
(92, 'Despesas de Exercícios Anteriores'),
(93, 'Indenizações e Restituições'),
(94, 'Indenizações e Restituições Trabalhistas'),
(95, 'Indenização pela Execução de Trabalhos de Campo'),
(96, 'Ressarcimento de Despesas de Pessoal Requisitado'),
(97, 'Aporte para Cobertura do Déficit Atuarial do RPPS'),
(99, 'A Classificar');

ALTER TABLE public.aux_dim_elemento_despesa ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read_aux_dim_elemento_despesa_anon" ON public.aux_dim_elemento_despesa;
CREATE POLICY "read_aux_dim_elemento_despesa_anon"
  ON public.aux_dim_elemento_despesa FOR SELECT TO anon, authenticated USING (true);

-- -------------------------------------------------------------
-- 2. Subfunção
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.aux_dim_subfuncao (
  codigo   SMALLINT PRIMARY KEY,
  descricao TEXT NOT NULL
);

TRUNCATE public.aux_dim_subfuncao;

INSERT INTO public.aux_dim_subfuncao (codigo, descricao) VALUES
( 31, 'Ação Legislativa'),
( 32, 'Controle Externo'),
( 61, 'Ação Judiciária'),
( 62, 'Defesa do Interesse Público no Processo Judiciário'),
( 91, 'Defesa da Ordem Jurídica'),
( 92, 'Representação Judicial e Extrajudicial'),
(121, 'Planejamento e Orçamento'),
(122, 'Administração Geral'),
(123, 'Administração Financeira'),
(124, 'Controle Interno'),
(125, 'Normatização e Fiscalização'),
(126, 'Tecnologia da Informação'),
(127, 'Ordenamento Territorial'),
(128, 'Formação de Recursos Humanos'),
(129, 'Administração de Receitas'),
(130, 'Administração de Concessões'),
(131, 'Comunicação Social'),
(151, 'Defesa Aérea'),
(152, 'Defesa Naval'),
(153, 'Defesa Terrestre'),
(181, 'Policiamento'),
(182, 'Defesa Civil'),
(183, 'Informação e Inteligência'),
(211, 'Relações Diplomáticas'),
(212, 'Cooperação Internacional'),
(241, 'Assistência ao Idoso'),
(242, 'Assistência ao Portador de Deficiência'),
(243, 'Assistência à Criança e ao Adolescente'),
(244, 'Assistência Comunitária'),
(271, 'Previdência Básica'),
(272, 'Previdência do Regime Estatutário'),
(273, 'Previdência Complementar'),
(274, 'Previdência Especial'),
(301, 'Atenção Básica'),
(302, 'Assistência Hospitalar e Ambulatorial'),
(303, 'Suporte Profilático e Terapêutico'),
(304, 'Vigilância Sanitária'),
(305, 'Vigilância Epidemiológica'),
(306, 'Alimentação e Nutrição'),
(331, 'Proteção e Benefícios ao Trabalhador'),
(332, 'Relações de Trabalho'),
(333, 'Empregabilidade'),
(334, 'Fomento ao Trabalho'),
(361, 'Ensino Fundamental'),
(362, 'Ensino Médio'),
(363, 'Ensino Profissional'),
(364, 'Ensino Superior'),
(365, 'Educação Infantil'),
(366, 'Educação de Jovens e Adultos'),
(367, 'Educação Especial'),
(368, 'Educação Básica'),
(391, 'Patrimônio Histórico, Artístico e Arqueológico'),
(392, 'Difusão Cultural'),
(421, 'Custódia e Reintegração Social'),
(422, 'Direitos Individuais, Coletivos e Difusos'),
(423, 'Assistência aos Povos Indígenas'),
(451, 'Infraestrutura Urbana'),
(452, 'Serviços Urbanos'),
(453, 'Transportes Coletivos Urbanos'),
(481, 'Habitação Rural'),
(482, 'Habitação Urbana'),
(511, 'Saneamento Básico Rural'),
(512, 'Saneamento Básico Urbano'),
(541, 'Preservação e Conservação Ambiental'),
(542, 'Controle Ambiental'),
(543, 'Recuperação de Áreas Degradadas'),
(544, 'Recursos Hídricos'),
(545, 'Meteorologia'),
(571, 'Desenvolvimento Científico'),
(572, 'Desenvolvimento Tecnológico e Engenharia'),
(573, 'Difusão do Conhecimento Científico e Tecnológico'),
(601, 'Promoção da Produção Vegetal'),
(602, 'Promoção da Produção Animal'),
(603, 'Defesa Sanitária Vegetal'),
(604, 'Defesa Sanitária Animal'),
(605, 'Abastecimento'),
(606, 'Extensão Rural'),
(607, 'Irrigação'),
(631, 'Reforma Agrária'),
(632, 'Colonização'),
(661, 'Promoção Industrial'),
(662, 'Produção Industrial'),
(663, 'Mineração'),
(664, 'Propriedade Industrial'),
(665, 'Normalização e Qualidade'),
(691, 'Promoção Comercial'),
(692, 'Comercialização'),
(693, 'Comércio Exterior'),
(694, 'Serviços Financeiros'),
(695, 'Turismo'),
(721, 'Comunicações Postais'),
(722, 'Telecomunicações'),
(751, 'Conservação de Energia'),
(752, 'Energia Elétrica'),
(753, 'Petróleo'),
(754, 'Álcool'),
(755, 'Gás Natural'),
(756, 'Nuclear'),
(757, 'Combustíveis Minerais'),
(781, 'Transporte Aéreo'),
(782, 'Transporte Rodoviário'),
(783, 'Transporte Ferroviário'),
(784, 'Transporte Hidroviário'),
(785, 'Transportes Especiais'),
(811, 'Desporto de Rendimento'),
(812, 'Desporto Comunitário'),
(813, 'Lazer'),
(841, 'Refinanciamento da Dívida Interna'),
(842, 'Refinanciamento da Dívida Externa'),
(843, 'Serviço da Dívida Interna'),
(844, 'Serviço da Dívida Externa'),
(845, 'Transferências'),
(846, 'Outros Encargos Especiais'),
(847, 'Transferências para a Educação Básica'),
(999, 'Reserva de Contingência');

ALTER TABLE public.aux_dim_subfuncao ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "read_aux_dim_subfuncao_anon" ON public.aux_dim_subfuncao;
CREATE POLICY "read_aux_dim_subfuncao_anon"
  ON public.aux_dim_subfuncao FOR SELECT TO anon, authenticated USING (true);
